#!/bin/bash
#Based on http://jetpackweb.com/blog/2009/07/20/bash-script-to-create-mysql-database-and-user/

BTICK='`'
EXPECTED_ARGS=3
E_BADARGS=65
MYSQL=`which mysql`

Q1="CREATE USER '$2'@'%' IDENTIFIED BY '$3';"
Q2="GRANT USAGE ON *.* TO '$2'@'%' IDENTIFIED BY '$3';"
Q3="CREATE DATABASE IF NOT EXISTS ${BTICK}$1${BTICK};"
Q4="GRANT ALL PRIVILEGES ON ${BTICK}$1${BTICK}.* TO '$2'@'%';"
Q5="GRANT ALL PRIVILEGES ON ${BTICK}$1\_%${BTICK}.* TO '$2'@'%';"
SQL="${Q1}${Q2}${Q3}${Q4}${Q5}"

if [ $# -ne $EXPECTED_ARGS ]
  then
  echo "Usage: $0 dbname dbuser dbpass"
  exit $E_BADARGS
fi

echo $p
$MYSQL -ucreatedb -e "$SQL"